### ISSUE TITLE
Bold button bug (Alternate bold and unbold)

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#115] opened 2016-09-19 18:03 UTC
Open the demo and clear it.

Type ddddd and click on bold. Type dddddd. Click on bold. Type ddddd. Strange behavior. The last text stay bold and a 'd' not bolded appear at the bottom

**Comment by maxiplay** [comment] 2016-09-19 18:04
Same bug with others buttons

**Comment by miztroh** [comment] 2016-09-26 19:04
Confirmed, but I think this is due to the selection bug.  Closing in favor of #112.

**Closed by miztroh** 2016-09-26 19:04 UTC
